### PR TITLE
Integrated spec and fixed N+1 issue

### PR DESCRIPTION
**Pull request by Simpleshaikh1**
In this PR, I collaborated with uzochukwuwinnie@gmail.com on this project,

Ensured that the N+1 problem is solved when fetching all posts and their comments for a user.
Before:
Screenshot (53)

Integration specs

Use Capybara to write integration tests for each view in your project.

Think on the flow of things and group the tests of page in a way that makes sense. For example, one test would check for the things in the page and another test for clicking links on it.

User index page:

I can see the username of all other users.
I can see the profile picture for each user.
I can see the number of posts each user has written.
When I click on a user, I am redirected to that user's show page.
After:

Screenshot (48)

user show page:

I can see the user's profile picture.
I can see the user's username.
I can see the number of posts the user has written.
I can see the user's bio.
I can see the user's first 3 posts.
I can see a button that lets me view all of a user's posts.
When I click a user's post, it redirects me to that post's show page.
When I click to see all posts, it redirects me to the user's post's index page.

User post index page:

I can see the user's profile picture.
I can see the user's username.
I can see the number of posts the user has written.
I can see a post's title.
I can see some of the post's body.
I can see the first comments on a post.
I can see how many comments a post has.
I can see how many likes a post has.
I can see a section for pagination if there are more posts than fit on the view.
When I click on a post, it redirects me to that post's show page.

Post show page:

I can see the post's title.
I can see who wrote the post.
I can see how many comments it has.
I can see how many likes it has.
I can see the post body.
I can see the username of each commentor.
I can see the comment each commentor left.
Be sure to include integration specs for any other features you may have implemented!

### CODE REVIEW

**Review by codepantha — COMMENTED** [review]
## Hi team 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project that doesn't have a valid code contribution from your coding partner. This is because simply modifying the README file does not count as a valid code contribution. Your coding partner needs to commit actual code. 🙏 



Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Abenezer-Tilahun** [comment]
Hi team 👋,
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [x] You have submitted a project that doesn't have a valid code contribution from your coding partner. This is because I noticed that the partner who initially only updated the README file added a commit related to updating the HTML code. This update does not align with the current project requirements.. 🙏 So kindly create new Pull request and contribute with your coding partner with the current project requirements.

- Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

#### Invalid Code Review Request does not count into the code reviews limit.

**Comment by Simpleshaikh1** [comment]
@Abenezer-Tilahun I do not understand what you mean by this statement "the partner who initially only updated the README file added a commit related to updating the HTML code". Do you imply that the commit message is the same thing?

**Comment by Abenezer-Tilahun** [comment]
Hello @Simpleshaikh1 commit messages  related to updating the HTML code. this commit is not related or does not align with the current project requirements that why?

**Review by Abenezer-Tilahun — APPROVED** [review]
Hi @Simpleshaikh1 @Wineshuga 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct Git-Flow.
✔️ Professional README  
✔️ Good Commit Messages.
✔️ Correctly Solved N+1 problem when fetching all posts and their comments for a user.
✔️ Correctly include integration specs for User index page and user show page.
✔️ Correctly include integration specs for User Post index page and post show page.
✔️ Good job for Implemented Blog app - integration specs for views and fix n+1 problems.
✔️ All Test cases are passing.

image



## Optional suggestions 
 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

**Pull request merged**
